### ISSUE TITLE
你好，我在安装的时候遇到一个bug

### ISSUE THREAD

**Issue by lklkdawei** [swoole/ext-orm#3]
`➜  ext-orm git:(master) ✗ php -v
PHP 7.3.5 (cli) (built: May  2 2019 12:42:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies`

安装步骤
1、phpize
2、chmod +x ./configure
3、./configure --with-php-config=/usr/bin/php-config
4、make
在第四步 make 的时候出现如下bug
![image](https://user-images.githubusercontent.com/3435608/58707468-a1fe6a80-83e7-11e9-82c5-291998552a5f.png)

**Comment by caohao-php** [comment]
你好，已经在最新版本解决，您下载最新的试试

**Comment by tzent** [comment]
After the last update I get some warnings

![Screenshot 2019-06-04 at 14 36 55](https://user-images.githubusercontent.com/3065451/58879855-e8e5ac00-86d6-11e9-80eb-973d73e91ddb.png)

**Comment by caohao-php** [comment]
> some
it fixed in the lastest update~
