### ISSUE TITLE
Compile error under macosx.

### ISSUE THREAD

**Issue by santalex** [swoole/ext-orm#6]
Last few lines bellow:

`/bin/sh /tmp/ext-orm/libtool --mode=link cc -DPHP_ATOM_INC -I/tmp/ext-orm/include -I/tmp/ext-orm/main -I/tmp/ext-orm -I/usr/local/Cellar/php/7.4.4/include/php -I/usr/local/Cellar/php/7.4.4/include/php/main -I/usr/local/Cellar/php/7.4.4/include/php/TSRM -I/usr/local/Cellar/php/7.4.4/include/php/Zend -I/usr/local/Cellar/php/7.4.4/include/php/ext -I/usr/local/Cellar/php/7.4.4/include/php/ext/date/lib  -DHAVE_CONFIG_H  -v    -o swoole_orm.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/ext-orm/modules  swoole_orm.lo src/memory.lo src/operator.lo src/string.lo src/array.lo 
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/swoole_orm.so -bundle  .libs/swoole_orm.o src/.libs/memory.o src/.libs/operator.o src/.libs/string.o src/.libs/array.o  
duplicate symbol '_swoole_orm_ce_ptr' in:
    .libs/swoole_orm.o
    src/.libs/memory.o
duplicate symbol '_swoole_orm_ce' in:
    .libs/swoole_orm.o
    src/.libs/memory.o
duplicate symbol '_swoole_orm_ce_ptr' in:
    .libs/swoole_orm.o
    src/.libs/operator.o
duplicate symbol '_swoole_orm_ce' in:
    .libs/swoole_orm.o
    src/.libs/operator.o
duplicate symbol '_swoole_orm_ce_ptr' in:
    .libs/swoole_orm.o
    src/.libs/string.o
duplicate symbol '_swoole_orm_ce' in:
    .libs/swoole_orm.o
    src/.libs/string.o
duplicate symbol '_swoole_orm_ce_ptr' in:
    .libs/swoole_orm.o
    src/.libs/array.o
duplicate symbol '_swoole_orm_ce' in:
    .libs/swoole_orm.o
    src/.libs/array.o
ld: 8 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [swoole_orm.la] Error 1
`

**Comment by caohao-php** [comment]
not suport mac os temporary~ sorry

**Comment by caohao-php** [comment]
> Last few lines bellow:
> 
> `/bin/sh /tmp/ext-orm/libtool --mode=link cc -DPHP_ATOM_INC -I/tmp/ext-orm/include -I/tmp/ext-orm/main -I/tmp/ext-orm -I/usr/local/Cellar/php/7.4.4/include/php -I/usr/local/Cellar/php/7.4.4/include/php/main -I/usr/local/Cellar/php/7.4.4/include/php/TSRM -I/usr/local/Cellar/php/7.4.4/include/php/Zend -I/usr/local/Cellar/php/7.4.4/include/php/ext -I/usr/local/Cellar/php/7.4.4/include/php/ext/date/lib -DHAVE_CONFIG_H -v -o swoole_orm.la -export-dynamic -avoid-version -prefer-pic -module -rpath /tmp/ext-orm/modules swoole_orm.lo src/memory.lo src/operator.lo src/string.lo src/array.lo cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/swoole_orm.so -bundle .libs/swoole_orm.o src/.libs/memory.o src/.libs/operator.o src/.libs/string.o src/.libs/array.o duplicate symbol '_swoole_orm_ce_ptr' in: .libs/swoole_orm.o src/.libs/memory.o duplicate symbol '_swoole_orm_ce' in: .libs/swoole_orm.o src/.libs/memory.o duplicate symbol '_swoole_orm_ce_ptr' in: .libs/swoole_orm.o src/.libs/operator.o duplicate symbol '_swoole_orm_ce' in: .libs/swoole_orm.o src/.libs/operator.o duplicate symbol '_swoole_orm_ce_ptr' in: .libs/swoole_orm.o src/.libs/string.o duplicate symbol '_swoole_orm_ce' in: .libs/swoole_orm.o src/.libs/string.o duplicate symbol '_swoole_orm_ce_ptr' in: .libs/swoole_orm.o src/.libs/array.o duplicate symbol '_swoole_orm_ce' in: .libs/swoole_orm.o src/.libs/array.o ld: 8 duplicate symbols for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [swoole_orm.la] Error 1 `

not suport mac os temporary~  sorry ，  i will be appreciate if you add mac os support peculiarity

**Comment by santalex** [comment]
its ok, i'll try a linux server.

**Comment by caohao-php** [comment]
> its ok, i'll try a linux server.

https://github.com/caohao-php/ycsocket  ,  you can see  example in this repositories
